export const categories = {
  Venues: ["Beach", "Garden", "Country", "Waterview", "Winery"],
  Florists: ["Traditional", "Modern", "Bohemian", "Vintage", "Rustic"],
  Photographers: ["Traditional", "Photojournalistic", "Candid", "Cultural"],
  Cakes: ["Traditional", "Modern", "Rustic", "Floral", "Themed"],
  Entertainment: [
    "Live Bands",
    "DJs",
    "Solo Musicians",
    "Magicians",
    "Photo Booths",
  ],
  "MCs and Celebrants": ["MCs", "Celebrants"],
  Catering: [
    "Traditional",
    "Modern",
    "Cultural",
    "Casual",
    "Gourmet",
    "Fine Dining",
  ],
  Transportation: ["Luxury", "Vintage", "Exotic", "Classic"],
};

export const features = {
  Venues: [
    "Ceremonies",
    "Receptions",
    "External Catering",
    "MC Services",
    "Amenities",
    "Accessible Location",
    "Outdoor",
    "Accomodation",
    "Parking",
    "Exceptional Menus",
    "Stunning Views",
  ],
  Florists: [
    "Ceremony Decor",
    "Reception Decor",
    "Custom Designs",
    "Rental Services",
    "Delivery & Setup",
    "Seasonal Blooms",
    "Bouquets",
    "Centerpieces",
  ],
  Photographers: [
    "Photo Editing",
    "Candid Shots",
    "Portrait Sessions",
    "Custom Albums",
    "Drone Photography",
    "Receptions",
    "Ceremonies",
    "Multiple Shooters",
  ],
  Cakes: [
    "Custom Design",
    "Delicious Flavors",
    "Elegant Presentation",
    "Fresh Ingredients",
    "Personalised Details",
    "Tiered Structure",
    "Edible Decorations",
    "Buttercream Frosting",
    "Fondant Finish",
    "Gluten-Free Options",
  ],
  Entertainment: [
    "Interactive Performers",
    "Custom Playlist",
    "Professional Lighting",
    "Photo Booth",
    "Live Music",
    "DJ Services",
    "Magical Moments",
    "Themed Entertainment",
    "Engaging MC",
    "Audience Participation",
  ],
  "MCs and Celebrants": [
    "MC and Celebrant",
    "Own Microphone",
    "Award Winner",
    "Free Consultation",
    "Run Sheet Creation",
    "Wedding Games",
    "Interstate Services",
  ],
  Catering: [
    "Custom Menus",
    "Professional Staff",
    "Flexible Packages",
    "On-Site Cooking",
    "Buffet Service",
    "Plated Meals",
    "Vegetarian Options",
    "Gluten-Free Options",
    "Dessert Stations",
    "Beverage Packages",
  ],
  Transportation: [
    "Luxury Fleet",
    "Chauffeur Service",
    "Flexible Booking",
    "24/7 Support",
    "GPS Navigation",
    "Child Seats",
    "Airport Transfers",
    "Insurance Coverage",
    "Fuel Efficiency",
    "Unlimited Mileage",
  ],
};
